# Use the official Python image with version 3.12.1
FROM python:3.12.1-slim

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Install PostgreSQL dependencies (required for psycopg2)
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project into the container
COPY . /app/

# Set environment variables for Django
ENV DJANGO_SETTINGS_MODULE=sakhiBackend.settings

# Expose the port Django runs on
EXPOSE 8000

# Run migrations and start Django server using Gunicorn
CMD ["gunicorn", "sakhiBackend.wsgi:application", "--bind", "0.0.0.0:8000"]
