# Generated by Django 5.1.1 on 2025-01-23 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_is_staff_user_date_joined_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follicle_no_r', models.IntegerField()),
                ('follicle_no_l', models.IntegerField()),
                ('skin_darkening', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('hair_growth', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('weight_gain', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('cycle_length', models.IntegerField()),
                ('amh', models.FloatField()),
                ('fast_food', models.FloatField()),
                ('cycle_r_i', models.IntegerField(choices=[(0, 'Irregular'), (1, 'Regular')])),
                ('fsh_lh', models.FloatField()),
                ('prl', models.FloatField()),
                ('pimples', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='NonClinicalDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_darkening', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('hair_growth', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('weight_gain', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('cycle_length', models.IntegerField()),
                ('fast_food', models.FloatField()),
                ('pimples', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
