# Generated by Django 5.1.5 on 2025-02-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_symptom_symptomcategory_symptomtrack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SymptomTrack',
        ),
    ]
