# Generated by Django 5.1.5 on 2025-02-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_symptomtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='user.symptomcategory'),
            preserve_default=False,
        ),
    ]
